#yaml document start with ----
---
- #this minus is required in yaml it indicate list of items. Playbook contains a list of play and every play will be a dictionary
#host: where you want to run your playbook
  hosts: client1
  
#vars: variable that will apply to the play
  vars: #is a keywoad
    motd_centos: "Welcome to Redhat ansible rocks2\n"
    motd_ubuntu: "Welcome to ubunut ansible rock2\n"
  tasks:
    - name: Exploring register
      command: hostname -s
      when:
        - ansible_distribution == 'RedHat' 
        - ansible_distribution_major_version | int <= 7
      register: test
    - name: install patch when changed
      yum:
        name: patch 
        state: present 
      when: test is skipped
    - name: print test
      debug:
        msg: "{{test.stdout}}"
    - name: check if apache is running or not
      shell: if ps -eaf| grep 'httpd'| grep -v grep > /dev/null; then echo 'process running';else echo 'process not running'
      register: app_proc_check
    - name: decision point to start patching
      fail: 
        msg: "{{inventory_hostname}}"
      when: app_proc_check.stdout = "process running"
    - name: update the kernal
      yum:
        name: kernal 5
        state: present