#yaml document start with ----
---
- #this minus is required in yaml it indicate list of items. Playbook contains a list of play and every play will be a dictionary
#host: where you want to run your playbook
  hosts: jump
  
#vars: variable that will apply to the play
  vars: #is a keywoad
    myurl: "https://releases.ansible.com/ansible/ansible-latest.tar.gz"
    mycrc: "sha256:https://releases.ansible.com/ansible/ansible-latest.tar.gz.sha"
    mydest: "/tmp/"
  tasks:
    - name: download file with proxy 
      get_url:
        url: "{{ myurl }}"
        dest: "{{ mydest }}"
        checksum: "{{ mycrc }}"
        mode: 0644
   #   environment:
    #    https_proxy: "http://example.com:3128"

