#yaml document start with ----
---
- #this minus is required in yaml it indicate list of items. Playbook contains a list of play and every play will be a dictionary
#host: where you want to run your playbook
  hosts: client1
  
#vars: variable that will apply to the play
  vars: #is a keywoad
    motd_centos: "Welcome to Redhat ansible rocks2\n"
    motd_ubuntu: "Welcome to ubunut ansible rock2\n"
  tasks:
    - name: creating user
      user:
        name: "{{ item.key }}"
        comment: "{{item.value.full_name}}"
      with_dict:
      #with_dic you can define key and key value
        james: #this is also an key
           full_name: James Bond #full name is key and value is jamesbond 
        kim:
           full_name: kim kard
        lily:
          full_name: lily lily 