#yaml document start with ----
---
- #this minus is required in yaml it indicate list of items. Playbook contains a list of play and every play will be a dictionary
#host: where you want to run your playbook
  hosts: client1
  
#vars: variable that will apply to the play
  vars: #is a keywoad
    motd_centos: "Welcome to Redhat ansible rocks2\n"
    motd_ubuntu: "Welcome to ubunut ansible rock2\n"
  tasks:
    - name: creating user
      user:
        name: "{{ item.key }}"
        comment: "{{item.value.full_name}}"
        state: absent
      with_dict:
      #with_dic you can define key and key value
        james: #this is also an key
           full_name: James Bond #full name is key and value is jamesbond 
        kim:
           full_name: kim kard
        lily:
          full_name: lily lily 
    - name: create user directory
      file:
        dest: "/home/{{ item.0 }}/{{ item.1 }}"
        owner: "{{ item.0 }}"
        group: "{{ item.0 }}"
        state: directory
      with_nested:
        - [james, lily, kim]
        - [photos, movies, document]
    - name: create authorized key 
      authorized_keys:
        user: james
        key: "{item}"
      with_files:
        - /root/.ssh/id_rsa.pub
    - name: create sequence directory
      files: 
        dest: "/home/james/gopal_{{item}}"
        state: directory
      with_sequence: start=0 end=100 stride=10