---
- #this minus is required in yaml it indicate list of items. Playbook contains a list of play and every play will be a dictionary
#host: where you want to run your playbook
  hosts: jump
  
#vars: variable that will apply to the play
  vars: #is a keywoad
    motd_centos: "Welcome to Redhat ansible rocks2\n"
    motd_ubuntu: "Welcome to ubunut ansible rock2\n"
  tasks:  
    - name: install apache
      shell: if ps -eaf| egrep 'apache2'| grep -v grep > /dev/null; then echo 'process_running'; else echo 'process_not_running'; fi
      ignore_errors: true 
      register: app_proc_check
    - debug: msg="{{ app_proc_check.stdout }}"
    - name: current kernal version 
      shell: uname -r 
      register: curr_ker