#yaml document start with ----
---
- #this minus is required in yaml it indicate list of items. Playbook contains a list of play and every play will be a dictionary
#host: where you want to run your playbook
  hosts: ansiblemaster
  gather_facts: False
#vars: variable that will apply to the play
  tasks:
    - name: generate an openssh key for ubuntu 
      openssh_keypair:
        path: ~/.ssh/client_id_rsa
  ######Host where our play will transfer private and public key
-
  hosts: bastion
  gather_facts: False
  tasks: 
    - name: copy the pub and pvt key to 
      copy: 
        owner: root 
        src: "{{ item.0 }}"
        dest: "{{ item.0 }}"
        mode: "{{ item.1 }}" 
      with_together:
        - [~/.ssh/client_id_rsa,~/.ssh/client_id_rsa.pub]
        - ["0600", "0644"]
- 
  hosts: endpoint
  gather_facts: False
  tasks:
    - name: Add public key to the client authorized_key file
      authorized_key:
        user: root 
        state: present 
        key: "{{ lookup('file','~/.ssh/client_id_rsa.pub')}}"
    